[package]
name = "ckb-script-ipc-common"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# TODO: update it to ckb-std 0.16.0 when it's published
ckb-std = { git = "https://github.com/nervosnetwork/ckb-std.git", default-features = false, features = ["allocator", "ckb-types", "dummy-atomic"], rev = "d74821c" }

serde = { version = "1.0.208", default-features = false, features = ["derive"] }
serde_molecule = { version = "1.1.0", default-features = false, features = ["alloc"] }
hex = { version = "0.4", default-features = false, features = ["alloc"]}
log = { version = "0.4", optional = true, default-features = false }


[features]
default = []
enable-logging = ["log"]
