name: Rust

on:
  pull_request:

jobs:
  develop:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: Prepare
      run: make prepare
    - name: Format & Clippy
      run: make clippy && cargo fmt -- --check
    - name: Build
      run: make build
    - name: Test
      run: make test