name: Rust

on:
  pull_request:
  push:

jobs:
  develop:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: Prepare
      run: make prepare
    - name: Format & Clippy
      run: make clippy && cargo fmt -- --check
    - name: Build
      run: make build
    - name: Test
      run: make test
    - name: Test on Rust 1.75
      run: rustup run --install 1.75.0 make test